runtime: java17
instance_class: F1

env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
